[package]
name = "composer-primitives"
version.workspace = true
edition.workspace = true
authors.workspace = true
license = "Apache-2.0"
description = "primitives types for composer"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0.107"
allocative = "0.3.0"
thiserror = "1.0.50"
itertools = "0.12.1"
tempfile = "3.2.0"
walkdir = "2"
anyhow = "1.0.65"
